package com.example.demo.entity;

import java.util.Date;

public class t001userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t001_userinfo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t001_userinfo.loginname
     *
     * @mbggenerated
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t001_userinfo.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t001_userinfo.mobileno
     *
     * @mbggenerated
     */
    private String mobileno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t001_userinfo.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t001_userinfo.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t001_userinfo.id
     *
     * @return the value of t001_userinfo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t001_userinfo.id
     *
     * @param id the value for t001_userinfo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t001_userinfo.loginname
     *
     * @return the value of t001_userinfo.loginname
     *
     * @mbggenerated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t001_userinfo.loginname
     *
     * @param loginname the value for t001_userinfo.loginname
     *
     * @mbggenerated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t001_userinfo.password
     *
     * @return the value of t001_userinfo.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t001_userinfo.password
     *
     * @param password the value for t001_userinfo.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t001_userinfo.mobileno
     *
     * @return the value of t001_userinfo.mobileno
     *
     * @mbggenerated
     */
    public String getMobileno() {
        return mobileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t001_userinfo.mobileno
     *
     * @param mobileno the value for t001_userinfo.mobileno
     *
     * @mbggenerated
     */
    public void setMobileno(String mobileno) {
        this.mobileno = mobileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t001_userinfo.qq
     *
     * @return the value of t001_userinfo.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t001_userinfo.qq
     *
     * @param qq the value for t001_userinfo.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t001_userinfo.addtime
     *
     * @return the value of t001_userinfo.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t001_userinfo.addtime
     *
     * @param addtime the value for t001_userinfo.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}